//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18052
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace Ork.Framework.ExampleDataSeederService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExampleDataSeederService.ExampleDataSeederService")]
    public interface ExampleDataSeederService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ExampleDataSeederService/Seed", ReplyAction="http://tempuri.org/ExampleDataSeederService/SeedResponse")]
        System.IAsyncResult BeginSeed(System.AsyncCallback callback, object asyncState);
        
        void EndSeed(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExampleDataSeederServiceChannel : Ork.Framework.ExampleDataSeederService.ExampleDataSeederService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExampleDataSeederServiceClient : System.ServiceModel.ClientBase<Ork.Framework.ExampleDataSeederService.ExampleDataSeederService>, Ork.Framework.ExampleDataSeederService.ExampleDataSeederService {
        
        private BeginOperationDelegate onBeginSeedDelegate;
        
        private EndOperationDelegate onEndSeedDelegate;
        
        private System.Threading.SendOrPostCallback onSeedCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ExampleDataSeederServiceClient() {
        }
        
        public ExampleDataSeederServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExampleDataSeederServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExampleDataSeederServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExampleDataSeederServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Der CookieContainer konnte nicht festgelegt werden. Stellen Sie sicher, dass die " +
                            "Bindung ein HttpCookieContainerBindingElement enthält.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SeedCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Ork.Framework.ExampleDataSeederService.ExampleDataSeederService.BeginSeed(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSeed(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Ork.Framework.ExampleDataSeederService.ExampleDataSeederService.EndSeed(System.IAsyncResult result) {
            base.Channel.EndSeed(result);
        }
        
        private System.IAsyncResult OnBeginSeed(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Ork.Framework.ExampleDataSeederService.ExampleDataSeederService)(this)).BeginSeed(callback, asyncState);
        }
        
        private object[] OnEndSeed(System.IAsyncResult result) {
            ((Ork.Framework.ExampleDataSeederService.ExampleDataSeederService)(this)).EndSeed(result);
            return null;
        }
        
        private void OnSeedCompleted(object state) {
            if ((this.SeedCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SeedCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SeedAsync() {
            this.SeedAsync(null);
        }
        
        public void SeedAsync(object userState) {
            if ((this.onBeginSeedDelegate == null)) {
                this.onBeginSeedDelegate = new BeginOperationDelegate(this.OnBeginSeed);
            }
            if ((this.onEndSeedDelegate == null)) {
                this.onEndSeedDelegate = new EndOperationDelegate(this.OnEndSeed);
            }
            if ((this.onSeedCompletedDelegate == null)) {
                this.onSeedCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSeedCompleted);
            }
            base.InvokeAsync(this.onBeginSeedDelegate, null, this.onEndSeedDelegate, this.onSeedCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Ork.Framework.ExampleDataSeederService.ExampleDataSeederService CreateChannel() {
            return new ExampleDataSeederServiceClientChannel(this);
        }
        
        private class ExampleDataSeederServiceClientChannel : ChannelBase<Ork.Framework.ExampleDataSeederService.ExampleDataSeederService>, Ork.Framework.ExampleDataSeederService.ExampleDataSeederService {
            
            public ExampleDataSeederServiceClientChannel(System.ServiceModel.ClientBase<Ork.Framework.ExampleDataSeederService.ExampleDataSeederService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginSeed(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("Seed", _args, callback, asyncState);
                return _result;
            }
            
            public void EndSeed(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("Seed", _args, result);
            }
        }
    }
}
